# Generated by Django 5.2.14 on 2026-05-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
