# Generated by Django 5.2.14 on 2026-05-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pais',
        ),
    ]
